/*
 Copyright (C) Yolla Media 2023
 https://portal.yollamedia.com
 Version: 3.3.0 / 7.54.3
 Release: 2023-08-25T13:54:25.558Z

*/
(function(){function u(c,a){if(!(c instanceof a))throw new TypeError("Cannot call a class as a function");}function A(c){"@babel/helpers - typeof";return A="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},A(c)}function ca(c){a:if("object"===A(c)&&null!==c){var a=c[Symbol.toPrimitive];if(void 0!==a){c=a.call(c,"string");if("object"!==A(c))break a;
throw new TypeError("@@toPrimitive must return a primitive value.");}c=String(c)}return"symbol"===A(c)?c:String(c)}function da(c,a){for(var d=0;d<a.length;d++){var b=a[d];b.enumerable=b.enumerable||!1;b.configurable=!0;"value"in b&&(b.writable=!0);Object.defineProperty(c,ca(b.key),b)}}function v(c,a,d){a&&da(c.prototype,a);d&&da(c,d);Object.defineProperty(c,"prototype",{writable:!1});return c}function q(c){if(void 0===c)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
return c}function O(c,a){O=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(d,b){d.__proto__=b;return d};return O(c,a)}function J(c,a){if("function"!==typeof a&&null!==a)throw new TypeError("Super expression must either be null or a function");c.prototype=Object.create(a&&a.prototype,{constructor:{value:c,writable:!0,configurable:!0}});Object.defineProperty(c,"prototype",{writable:!1});a&&O(c,a)}function K(c,a){if(a&&("object"===A(a)||"function"===typeof a))return a;if(void 0!==a)throw new TypeError("Derived constructors may only return object or undefined");
return q(c)}function t(c){t=Object.setPrototypeOf?Object.getPrototypeOf.bind():function(a){return a.__proto__||Object.getPrototypeOf(a)};return t(c)}function h(c,a,d){a=ca(a);a in c?Object.defineProperty(c,a,{value:d,enumerable:!0,configurable:!0,writable:!0}):c[a]=d;return c}function y(c){return"undefined"===typeof c}function C(c,a){return Object.prototype.toString.call(c)==="[object "+a+"]"}function P(c){if(!c)return!0;if(c&&Array.isArray(c)||C(c,"String"))return!(0<c.length);for(var a in c)if(Object.prototype.hasOwnProperty.call(c,
a))return!1;return!0}function ea(c,a){if(C(c,"Object")&&C(a,"String")&&a){var d=a.indexOf("."),b=0>d?a:a.substring(0,d);c=c.hasOwnProperty(b)?c[b]:void 0;return 0>d?c:ea(c,a.substring(d+1))}}function B(){B="undefined"!==typeof Reflect&&Reflect.get?Reflect.get.bind():function(c,a,d){var b;for(b=c;!Object.prototype.hasOwnProperty.call(b,a)&&(b=t(b),null!==b););if(b)return b=Object.getOwnPropertyDescriptor(b,a),b.get?b.get.call(3>arguments.length?c:d):b.value};return B.apply(this,arguments)}function Da(c){var a=
Ea();return function(){var d=t(c);if(a){var b=t(this).constructor;d=Reflect.construct(d,arguments,b)}else d=d.apply(this,arguments);return K(this,d)}}function Ea(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(c){return!1}}function Q(c){return c?(c^16*Math.random()>>c/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,
Q)}function fa(){try{return window.localStorage}catch(c){return new R}}function Fa(c){var a=Ga();return function(){var d=t(c);if(a){var b=t(this).constructor;d=Reflect.construct(d,arguments,b)}else d=d.apply(this,arguments);return K(this,d)}}function Ga(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(c){return!1}}function S(){return window.innerWidth||
document.documentElement.clientWidth||document.body.clientWidth||0}function T(){return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight||0}function Ha(c){var a=Ia();return function(){var d=t(c);if(a){var b=t(this).constructor;d=Reflect.construct(d,arguments,b)}else d=d.apply(this,arguments);return K(this,d)}}function Ia(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,
[],function(){})),!0}catch(c){return!1}}function U(c){if("string"==typeof c)return c;if(Ja(c)){for(var a=-1,d=null==c?0:c.length,b=Array(d);++a<d;)b[a]=U(c[a],a,c);return b+""}if(ha(c))return ia?ia.call(c):"";a=c+"";return"0"==a&&1/c==-Ka?"-0":a}function ja(c,a){var d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"floor";if(0>=a)throw Error("invalid roundTo");if(c<=a)return c;for(var b=c,e=1,g=0;!Number.isSafeInteger(a);)e*=10,a*=10,g++;d=Math[d](c*e/a);0<d&&(b=d*a/e);return La(b,g)}function Ma(c){var a=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:window.location.href,d=c.replace(/[[\]]/g,"\\$&");return(a=(new RegExp("[?&]".concat(d,"(=([^&#]*)|&|#|$)"))).exec(a))?a[2]?decodeURIComponent(a[2].replace(/\+/g," ")):"":null}function Na(c){var a=Oa();return function(){var d=t(c);if(a){var b=t(this).constructor;d=Reflect.construct(d,arguments,b)}else d=d.apply(this,arguments);return K(this,d)}}function Oa(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;
if("function"===typeof Proxy)return!0;try{return Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){})),!0}catch(c){return!1}}function ka(c,a,d){var b=3<arguments.length&&void 0!==arguments[3]?arguments[3]:{};if(document.querySelector('script[src="'.concat(c,'"]')))return a&&a.call(void 0),Promise.resolve(!0);var e=document.createElement("script");e.src=c;e.async=!0;for(var g in b)Object.prototype.hasOwnProperty.call(b,g)&&e.setAttribute(g,b[g]+"");return new Promise(function(f,
k){e.onload=function(){a&&a();f(!0)};e.onerror=function(){d&&d();k()};document.head.appendChild(e)})}function V(){return/complete|interactive|loaded/.test(document.readyState)}function la(c){return(c=c.match(/(\d+)(\.\d+)+/))?c[0]:""}function ma(c,a){if(c===a)return 0;c=c.split(".");a=a.split(".");for(var d=0;d<a.length;d++){var b=~~a[d],e=~~c[d];if(b>e)return 1;if(b<e)break}return-1}function na(c){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,d=m.getOption("YMPB_CUSTOM_JS");if("function"===
typeof d)try{d.call()}catch(k){window.console.error("CUSTOM_JS_ERROR")}var b=null,e=function n(){l.inited||(l.inited=!0,clearTimeout(b),document.removeEventListener("readystatechange",g,!1),document.removeEventListener("DOMContentLoaded",n,!1),a?ka(c,function(){try{l.init(m,a)}catch(p){window.console.error("Tag Error!")}}):ka(c))},g=function(){V()&&e()};d=1E3*Math.max(0,m.getOption("DELAY"));var f=1E3*m.getOption("MAX_DELAY");f=f>d?f:0;V()?e():(setTimeout(function(){V()?e():(document.addEventListener("DOMContentLoaded",
e,!1),document.addEventListener("readystatechange",g,!1))},d),0<f&&(b=setTimeout(function(){e()},f)))}Storage.prototype.readConverter||(Storage.prototype.readConverter=function(c){if(null===c)return null;try{return JSON.parse(c)}catch(a){return c}});Storage.prototype.keys||(Storage.prototype.keys=function(){return Object.keys(this)});Storage.prototype.writeConverter||(Storage.prototype.writeConverter=function(c){if("string"===typeof c)return c;var a="";try{a=JSON.stringify(c)}catch(d){a=c+""}return a});
Date.prototype.stdTimezoneOffset||(Date.prototype.stdTimezoneOffset=function(){var c=new Date(this.getFullYear(),0,1),a=new Date(this.getFullYear(),6,1);return Math.max(c.getTimezoneOffset(),a.getTimezoneOffset())});Date.prototype.dst||(Date.prototype.dst=function(){return this.getTimezoneOffset()<this.stdTimezoneOffset()});Number.prototype.toFixedNoRounding||(Number.prototype.toFixedNoRounding=function(c){var a=this.toString().match(new RegExp("^-?\\d+(?:\\.\\d{0,"+c+"})?","g"));a=a?a[0]:this.toString();
var d=a.indexOf(".");if(-1===d)return a+"."+"0".repeat(c);c=c-(a.length-d)+1;return 0<c?a+"0".repeat(c):a});var w,x=new Date,L={DEBUG:!1,DEBUG_PBJS:!1,USE_PBJS_BID_CACHE:!1,USE_YMPB_BID_CACHE:!1,CONSOLE_ENABLED:!1,MAX_SLOTS:50,ENABLE_CUSTOM_TRACKER:!1,DIAGNOSIS_GA_ACCOUNT:"UA-125030536-7",DIAGNOSIS_GA_ACCOUNT_2:"",YMPB_OPTION_TRACKING:{YMPB_VARIANT:"yvariant=%VALUE%"},DELAY:0,MAX_DELAY:0,DOMAIN_ID:void 0,ENABLE_ANALYTICS:!0,GA_ACCOUNT:"",CROSS_DOMAIN_GA_ACCOUNT:"",GA_CLIENT_TYPE:"ga4",YMPB_EVENT_CATEGORY:"Wins",
YMPB_TEMPLATE_ABTEST:!0,REGIONAL_CODE:"",YMPB_CUSTOM_CSS:"",YMPB_CUSTOM_JS:null,TCF_VERSION:"2.0",GDPR_ENABLED:!1,YMPB_GDPR_UI:!0,YMPB_GDPR_UI_LAYOUT:"",YMPB_USP:x.getTimezoneOffset()===(x.dst()?420:480),YMPB_USP_UI:!0,YMPB_USP_CONTAINER:"",CHECKING_BETTER_ADS:!0,YMPB_TABLET_SLOTS:"mobile",YMPB_DESKTOP_SLOTS:"desktop",YMPB_MOBILE_SLOTS:"mobile",YMPB_BASE_INDEX:"9999",YMPB_NOT_RUN_CHECKER:"body.ympb_no_ads",YMPB_AUTO_INSERT:[],YMPB_TEMPLATE_CSS:"",YMPB_COLLAPSE_EMPTY:!1,YMPB_WRAPPER_MAX_HEIGHT:!1,
YMPB_WRAPPER_LEADER_MAX_HEIGHT:!1,YMPB_ENABLE_FLUID_SIZE:!1,YMPB_ENABLE_FLUID_FROM_AUTOSIZE:!1,YMPB_ENABLE_SMALLER_SIZE:!1,YMPB_USE_CONTAINER_SIZE:!1,ENABLE_S2S:!1,S2S_CONFIG:{},YMPB_SFLOOR:0,YMPB_PB_REDUCE:.01,BIDDERS:[],YMPB_BIDDER_TIMEOUT:3500,YMPB_AUCTION_TIMEOUT:3500,MAX_REQUESTS_PER_ORIGIN:4,YMPB_INCLUDE_DEALS:!1,DISABLE_AJAX_TIMEOUT:!1,ENABLE_SEND_ALL_BIDS:!0,ENABLE_SEND_ALL_VIDEO_BIDS:!0,ENABLE_USER_SYNC:!0,USER_SYNC_FILTER:{iframe:{bidders:"*",filter:"include"}},ENUM_SCHAIN_VALIDATION:"strict",
YMPB_PUBLISHER_ID:"",YMPB_SINGLE_REQUEST:!0,CHILD_DIRECTED_TREATMENT:!1,EMBEDDED_URL_TAIL_SLASH:!1,EMBEDDED_URL_HOST_ONLY:!1,YMPB_BID_CACHE_TTL:180,YMPB_VIDEO_BID_MIN_TTL:180,YMPB_VIDEO_BID_MAX_TTL:180,TIMEOUT_BUFFER:"400",YMPB_BID_CACHE_MIN_TTL_OVERRIDE:1,YMPB_CACHE_SWAPPING:!0,YMPB_CPM_TARGET_MIN:.01,YMPB_CACHE_SP_LOGIC:!1,YMPB_CACHE_SP_THRESHOLD:0,YMPB_CACHE_SP_TTL_BUFFER:10,YMPB_CACHE_MAX:100,YMPB_CACHE_STORAGE_SIZE:0,BIDDER_LABELS_REFRESHING:[],REFRESH_IGNORE_VIEW_STATUS:[],REFRESH_IGNORE_ADX_VIEW_STATUS:!1,
YMPB_DESTROY_BEFORE_REFRESH:!1,YMPB_DEFAULT_REFRESHRATE:"30",YMPB_REFRESHRATE_MIN:"30",YMPB_REFRESHRATE_TWO:0,YMPB_REFRESHRATE_THREE:0,REFRESHRATE_ONE_LIMIT:0,REFRESHRATE_TWO_LIMIT:0,REFRESHRATE_THREE_LIMIT:0,YMPB_REFRESH_RATE_NOFILL:"30",YMPB_USE_CACHE_POSTAUCTION:!1,YMPB_REFRESH_UNVIEWED:!1,YMPB_REFRESH_NOT_INVIEW:!1,REFRESH_VISIBLE_FROM_HIDDEN:!1,YMPB_FORCE_REFRESH:0,YMPB_FORCE_REFRESH_ACTIVE:0,BIDDER_LABELS_PREFETCHING:[],BIDDER_LABELS_INITING:[],BIDDER_LABELS_INITCACHING:[],YMPB_ENABLE_ADDITIONAL_BIDS:0,
BIDDER_LABELS_PRECACHING:[],BIDDER_LABELS_PRECACHING_2:[],YMPB_PRECACHE_MAX_BIDS:"50",YMPB_FILTER_MIN_CPM:"0",YMPB_FILTER_MIN_TTL:"3",YMPB_PRECACHE_INTERVAL:"5",YMPB_PRECACHE_INTERVAL_2:"60",YMPB_PRECACHE_MULTIPLIER:"1",YMPB_PRECACHE_MULTIPLIER_2:"1",YMPB_ENABLE_SWAPPING:!1,YMPB_USE_RAF_API:!0,SWAP_OVERLAP:.5,SWAP_SIZE_ON_INIT:!0,SWAPPING_INTERVAL:"7",SWAP_IGNORE_BIDDERS:[],DYNAMIC_LOAD_SCREEN_VH:2,YMPB_AD_FOOTER_ENABLED:!1,YMPB_AD_FOOTER_TEXT:"",YMPB_AD_FOOTER_TEXT_TO_ALL:!1,ADHESION_ENABLED:!0,
ADHESION_ENABLECLOSE:!0,ADHESION_BG_COLOR:"",YMPB_MEDREC_TO_MULTI:{multiMode:"dynamic",maxSlots:2,maxSize:"",slotSpacing:20,insertGrid:"1x0"},YMPB_MEDREC_TO_MULTI_NUM:-1,YMPB_LEADERBOARD_TO_MULTI:{multiMode:"dynamic",maxSlots:2,maxSize:"",slotSpacing:20,insertGrid:"0x0"},YMPB_LEADERBOARD_TO_MULTI_NUM:-1,BIDDER_LABELS_IGNORE_ON_MULTI:[],PREROLL_WIDTH:100,PREROLL_RESPONSIVE:!1,YMPB_VIDEO_SKIP_TIMER:8,YMPB_VIDEO_VOLUME:0,PREROLL_MAX_DURATION:0,PREROLL_COUNTDOWN_MSG:"",PREROLL_INVIEW_AUTOPLAY:!0,PREROLL_ASPECT_RATIO:0,
YMPB_ENABLE_CLEANIO_SCRIPT:!1,YMPB_ENABLE_BLOCKTHROUGH:!1,YMPB_ENABLE_WITH_BLOCKER:!1,YMPB_VIDEO_TIMEOUT:10,YMPB_VIDEO_SFLOOR:0,YMPB_VIDEO_AUTOPLAY:!1,YMPB_VIDEO_FULLSCREEN:!1,PREROLL_RETRY:0,NATIVE_CONFIG:{},PREROLL_CONFIG:{},ENABLE_NATIVE:!1,ENABLE_INTERSTITIAL:!1,YMPB_PRELOAD_TIMEOUT:750,YMPB_PRELOAD_VERSION:"",YMPB_ENABLE_CACHE:(w={},h(w,"banner",!0),h(w,"native",!0),h(w,"video",!1),w),YMPB_ENABLE_VIDEO_CACHE:!1,YMPB_FPS_LIMIT:0,YMPB_MEMORY_LIMIT:0,RENDER_NOFILL:!1,ENABLE_DISPLAY_IN_PREROLL:0,
ENABLE_GPID:!1,YMPB_FORCE_QUANTCAST:!1},W=function(){function c(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"";u(this,c);h(this,"_namespace","");h(this,"_engine",void 0);h(this,"_supported",!1);this._engine=a;this._namespace=d;this.init()}v(c,[{key:"init",value:function(){this.test()}},{key:"test",value:function(){try{this.set(c._testkey,!0),this._supported=!0===this.get(c._testkey),this.remove(c._testkey)}catch(a){this._supported=!1}return this.supported()}},{key:"supported",
value:function(){return this._supported}},{key:"get",value:function(a){a=this._engine.getItem("".concat(this._namespace).concat(".").concat(a));return null===a?null:this._engine.readConverter(a)}},{key:"getAll",value:function(){var a=this;return this.keys().map(function(d){return a.get(d)})}},{key:"set",value:function(a,d){null===d&&this.remove(a);d=this._engine.writeConverter(d);this._engine.setItem("".concat(this._namespace).concat(".").concat(a),d);return d}},{key:"remove",value:function(a){this._engine.removeItem("".concat(this._namespace).concat(".").concat(a))}},
{key:"removeBy",value:function(a){var d=this;this.keys().forEach(function(b){a(b)&&d.remove(b)})}},{key:"keys",value:function(){var a="".concat(this._namespace).concat("."),d=this._engine.keys().filter(function(b){return 0===b.indexOf(a)});d=d.map(function(b){return b.replace(a,"")});return d.sort()}},{key:"flush",value:function(){}}]);return c}();h(W,"_testkey","__YMPB_TEST_KEY__");var oa=function(c){function a(b,e,g){var f;u(this,a);b=d.call(this,b,e||"");h(q(b),"_store",void 0);h(q(b),"_isNew",
!1);h(q(b),"_key",void 0);h(q(b),"_ttl",void 0);b._key=g.key;b._ttl=g.ttl;b._store=B((f=q(b),t(a.prototype)),"get",f).call(f,b._key);b._store&&b._store.value||(b._store={value:{}});return b}J(a,c);var d=Da(a);v(a,[{key:"values",get:function(){return null===this._store?{}:this._store.value}},{key:"isNew",get:function(){return this._isNew}},{key:"createdAt",get:function(){return this._store.created_at}},{key:"sync",value:function(){this._store=B(t(a.prototype),"get",this).call(this,this._key)}},{key:"get",
value:function(b){return this._store.value[b]}},{key:"set",value:function(b,e){null===e?this.remove(b):this._store.value[b]=e}},{key:"remove",value:function(b){delete this._store.value[b]}},{key:"isValid",value:function(){return null!==this._store&&this._store.expires>Date.now()}},{key:"create",value:function(b){var e=Date.now();this._isNew=!0;this._store={value:b,created_at:e,updated_at:e,expires:e+1E3*this._ttl,ttl:this._ttl};this.update()}},{key:"extend",value:function(){var b=0<arguments.length&&
void 0!==arguments[0]?arguments[0]:0,e=Date.now();this._store.updated_at=e;this._store.expires=e+1E3*(b||this._ttl);this.update()}},{key:"update",value:function(b){C(this._store.value,"Object")&&C(b,"Object")&&Object.assign(this._store.value,b);this._store.updated_at=Date.now();B(t(a.prototype),"set",this).call(this,this._key,this._store)}},{key:"delete",value:function(){B(t(a.prototype),"remove",this).call(this,this._key)}}]);return a}(W),R=function(){function c(){u(this,c);h(this,"_store",{})}v(c,
[{key:"getItem",value:function(a){return this._store.hasOwnProperty(a)?this._store[a]:null}},{key:"setItem",value:function(a,d){this._store[a]=d}},{key:"removeItem",value:function(a){delete this._store[a]}},{key:"readConverter",value:function(a){return a}},{key:"writeConverter",value:function(a){return a}},{key:"keys",value:function(){return Object.keys(this._store)}}]);return c}(),pa=function(){function c(){u(this,c);h(this,"_defaultOptions",{desktop:{}});h(this,"_cases",[]);h(this,"_activityCaseIndex",
0)}v(c,[{key:"init",value:function(a){this._defaultOptions=a}},{key:"activityCaseIndex",get:function(){return this._activityCaseIndex},set:function(a){this._activityCaseIndex=this.isValidCaseIndex(a)?a:0}},{key:"activityCase",get:function(){return this._cases[this.activityCaseIndex]}},{key:"getCaseByIndex",value:function(a){return 0>a||a>=this._cases.length?null:this._cases[a]}},{key:"isValidCaseIndex",value:function(a){return-1<a&&a<this._cases.length}},{key:"flatOptions",value:function(a){var d=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:"desktop",b={};if(!a)return b;Object.assign(b,a&&a.desktop?a.desktop:{});"desktop"!==d&&a&&a[d]&&Object.assign(b,a[d]||{});return b}},{key:"getMacroOptionsByIndex",value:function(){var a=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"desktop",d=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"",b=this._defaultOptions.desktop,e=this.getCaseByIndex(0<arguments.length&&void 0!==arguments[0]?arguments[0]:-1);e&&(Object.assign(b,this.flatOptions(e.macro_options,
a)),d&&e.geo_target_options&&Object.assign(b,this.flatOptions(e.geo_target_options[d],a)));return b}},{key:"addCase",value:function(a){this._cases.push(a)}},{key:"addCases",value:function(a){if(a&&a.length)for(var d=0;d<a.length;d++)this.addCase(a[d])}},{key:"randomlySetCase",value:function(){if(2>this._cases.length)this._activityCaseIndex=this._cases.length-1;else{for(var a=0,d=[],b=0;b<this._cases.length;b++){var e=this._cases[b];a+=e.weight;d.push({name:b,weight:e.weight})}a=Math.round(Math.random()*
a)+1;for(var g=e=0;g<d.length;g++)if(b=e,e+=d[g].weight,a>b&&a<=e){this._activityCaseIndex=d[g].name;break}}return this._activityCaseIndex}}],[{key:"getInstance",value:function(){c.instance||(c.instance=new c);return c.instance}}]);return c}();h(pa,"instance",void 0);var Pa=function(){function c(){u(this,c);h(this,"_isMobile",!1);h(this,"_isTablet",!1);h(this,"_isPhone",!1);h(this,"_isRetina",window.retina||1<window.devicePixelRatio);h(this,"_isNewIpad",!1===/iPhone/i.test(window.navigator.userAgent)&&
!0===/Mac/i.test(window.navigator.userAgent)&&!y(window.navigator.maxTouchPoints)&&2<window.navigator.maxTouchPoints);h(this,"_deviceType","desktop");h(this,"_browserType","unknown");h(this,"_oprateSystemType","unknown");h(this,"_slotType","desktop");this.checkDeviceType();this.checkBrowserType();this.checkOsType()}v(c,[{key:"isMobile",get:function(){return this._isMobile}},{key:"isTablet",get:function(){return this._isTablet}},{key:"isPhone",get:function(){return this._isPhone}},{key:"isRetina",
get:function(){return this._isRetina}},{key:"deviceType",get:function(){return"unknown"===this._deviceType?"desktop":this._deviceType},set:function(a){this._deviceType=a}},{key:"slotType",get:function(){return this._slotType},set:function(a){this._slotType=a}},{key:"browserType",get:function(){return this._browserType}},{key:"oprateSystemType",get:function(){return this._oprateSystemType}},{key:"autoplayAvailableOnDevice",get:function(){return!("firefox"===this._browserType||"safari"===this._browserType||
"ios"===this._oprateSystemType)}},{key:"resetSlotType",value:function(a){a=a.getOptions();switch(this._deviceType){case "tablet":this.slotType=a.YMPB_TABLET_SLOTS||"desktop";break;case "mobile":this.slotType=a.YMPB_MOBILE_SLOTS||"mobile";break;default:this.slotType=a.YMPB_DESKTOP_SLOTS||"desktop"}}},{key:"switchSlotType",value:function(a){this.slotType=a}},{key:"checkDeviceType",value:function(){!y(window.orientation)||this._isNewIpad?this._isMobile=!0:this._isMobile=c.test(/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/i);
this._isMobile?this._isNewIpad||c.test(/(tablet|ipad|playbook|silk)/i)||c.test(/android/i)&&!c.test(/android(.*mobile)/i)?(this._isTablet=!0,this.deviceType="tablet"):(this._isPhone=!0,this.deviceType="mobile"):this.deviceType="desktop"}},{key:"checkBrowserType",value:function(){switch(!0){case c.test(/edg/i):this._browserType="edge";break;case c.test(/opr/i)&&(!!window.opr||!!window.opera):this._browserType="opera";break;case c.test(/chrome/i)&&!!window.chrome:this._browserType="chrome";break;case c.test(/trident/i):this._browserType=
"ie";break;case c.test(/firefox/i):this._browserType="firefox";break;case c.test(/safari/i):this._browserType="safari";break;default:this._browserType="unknown"}}},{key:"checkOsType",value:function(){switch(!0){case c.test(/(iPhone|iPad|iPod|like Mac)/):this._oprateSystemType="ios";break;case c.test(/Win/):this._oprateSystemType="windows";break;case c.test(/Mac/):this._oprateSystemType="macos";break;case c.test(/Linux/):this._oprateSystemType="linux";break;case c.test(/Android/):this._oprateSystemType=
"android";break;default:this._oprateSystemType="unknown"}}}],[{key:"test",value:function(a){return a.test(window.navigator.userAgent)}}]);return c}(),X;(function(c){c.GET="get";c.POST="post";c.PUT="put";c.DELETE="delete"})(X||={});var z;(function(c){c.ABORT="abort";c.ERROR="error";c.TIMEOUT="timeout"})(z||={});var M=function(){function c(){u(this,c)}v(c,null,[{key:"isAbsoluteURL",value:function(a){return/^([a-z][a-z\d\+\-\.]*:)?\/\//i.test(a)}},{key:"combineURLs",value:function(a,d){return d?a.replace(/\/+$/,
"")+"/"+d.replace(/^\/+/,""):a}}]);return c}(),Qa=function(){function c(a){u(this,c);h(this,"_baseUrl",void 0);this._baseUrl=a.baseUrl}v(c,[{key:"get",value:function(a,d,b){a=this.request(X.GET,a);a.then(function(e){d&&d(e)}).catch(function(e){b&&b(e)});return a}},{key:"post",value:function(a,d,b){return this.request(X.POST,a).then(function(e){d&&d(e)}).catch(function(e){b&&b(e)})}},{key:"request",value:function(a,d){var b=0,e=M.isAbsoluteURL(d.url)?d.url:M.combineURLs(this._baseUrl,d.url),g=new XMLHttpRequest,
f=d.responseType||"json";f&&"json"!==f&&(g.responseType=f);d.mimeType&&g.overrideMimeType(d.mimeType);return new Promise(function(k,n){function p(r){30>b++?(d.timout+=250,c.do(e,a,d,g)):n(r)}g.onreadystatechange=function(){if(g&&g.readyState===XMLHttpRequest.DONE)if(0!==g.status||g.responseURL&&0===g.responseURL.indexOf("file:")){var r={data:"json"===f?g.responseText:g.response,status:g.status,statusText:g.statusText};400<=r.status?(d.requestTracker&&d.requestTracker(z.ERROR,d.timout),p(z.ERROR)):
(d.requestTracker&&d.requestTracker("success",d.timout),k(r))}else k({})};g.onabort=function(){d.requestTracker&&d.requestTracker(z.ABORT,d.timout);p(z.ABORT)};g.ontimeout=function(){d.requestTracker&&d.requestTracker(z.TIMEOUT,d.timout);p(z.TIMEOUT)};g.onerror=function(){d.requestTracker&&d.requestTracker(z.ERROR,d.timout);p(z.ERROR)};c.do(e,a,d,g)})}}],[{key:"do",value:function(a,d,b,e){var g=b.data,f=b.headers;e.open(d.toUpperCase(),a,b.async);e.timeout=b.timout||1250;for(var k in f)Object.prototype.hasOwnProperty.call(f,
k)&&e.setRequestHeader(k,f[k]);e.send(g)}}]);return c}(),Ra={accountId:"52a8e13e-aca0-47ee-a46f-9d908a3dff59",enabled:!1,testing:!1,timeout:1800,adapter:"prebidServer",endpoint:"https://prebid.adnxs.com/pbs/v1/openrtb2/auction",syncEndpoint:"https://prebid.adnxs.com/pbs/v1/cookie_sync",cookieSet:!0,cookiesetUrl:"https://acdn.adnxs.com/cookieset/cs.js",bidders:[],bidderControl:{},defaultTtl:L.YMPB_BID_CACHE_MIN_TTL_OVERRIDE},Sa=function(c){function a(){u(this,a);var b=d.call(this,fa(),"YMPB_OPTIONS",
{key:"_CASE_SESSION",ttl:1800});b.values.uuid||(b.values.uuid=Q());return b}J(a,c);var d=Fa(a);v(a,[{key:"uuid",get:function(){return this.values.uuid}},{key:"cv0",get:function(){this.sync();return this.values.cv0?+this.values.cv0:0},set:function(b){this.values.cv0=b;this.update(this.values)}},{key:"trackAt",get:function(){return this.values.track_at?+this.values.track_at:0},set:function(b){this.values.track_at=b;this.update(this.values)}},{key:"getTtl",value:function(){var b=new Date,e=b.getTimezoneOffset()/
60;e=23-(new Date((new Date).setHours((new Date).getHours()+e-5))).getHours();var g=new Date(b);g.setHours(g.getHours()+e);g.setMinutes(59);g.setSeconds(59);b=(g.getTime()-b.getTime())/1E3;return 1800>b?b:1800}},{key:"createSession",value:function(b){this.create({name:b,random:Math.ceil(10*Math.random()),uuid:this.uuid||Q(),cv0:0,track_at:0})}},{key:"isValid",value:function(){return B(t(a.prototype),"isValid",this).call(this)&&216E5>Date.now()-this.createdAt&&-1<this.values.name}},{key:"extend",value:function(){B(t(a.prototype),
"extend",this).call(this,this.getTtl())}}]);return a}(oa),Ta=function(){function c(a,d){u(this,c);h(this,"x",void 0);h(this,"y",void 0);this.x=a;this.y=d}v(c,[{key:"top",get:function(){return this.y}},{key:"left",get:function(){return this.x}},{key:"equals",value:function(a,d){return this.x===+a&&this.y===+d}},{key:"isZero",value:function(){return 0===this.x&&0===this.y}},{key:"set",value:function(a,d){this.x=a;this.y=d;return this}},{key:"getCoordinate",value:function(){return{x:this.x,y:this.y}}},
{key:"clone",value:function(){return new c(this.x,this.y)}},{key:"toString",value:function(){return"(".concat(this.x,", ").concat(this.y,")")}},{key:"map",value:function(a){this.x=a.call(this,this.x);this.y=a.call(this,this.y);return this}},{key:"add",value:function(a,d){this.x+=a;this.y+=d;return this}},{key:"subtract",value:function(a,d){this.x-=a;this.y-=d;return this}},{key:"symmetry",value:function(a,d){this.x=a-this.x;this.y=d-this.y;return this}},{key:"scale",value:function(a){this.x*=a;this.y*=
a;return this}},{key:"distance",value:function(a){return{x:a.x-this.x,y:a.y-this.y}}}]);return c}();w=function(){function c(a,d,b,e){u(this,c);h(this,"left",void 0);h(this,"top",void 0);h(this,"right",void 0);h(this,"bottom",void 0);this.left=a;this.top=d;this.right=a+b;this.bottom=d+e}v(c,[{key:"y",get:function(){return this.top},set:function(a){var d=this.top-a;this.top=a;this.bottom-=d}},{key:"size",get:function(){return[this.width,this.height]}},{key:"x",get:function(){return this.left},set:function(a){var d=
this.left-a;this.left=a;this.right-=d}},{key:"width",get:function(){return this.right-this.left},set:function(a){this.right=this.left+a}},{key:"height",get:function(){return this.bottom-this.top},set:function(a){this.bottom=this.top+a}},{key:"isEmpty",value:function(){return this.left>=this.right||this.top>=this.bottom}},{key:"equals",value:function(a){return null!=a&&(this.isEmpty()&&a.isEmpty()||this.top===a.top&&this.left===a.left&&this.bottom===a.bottom&&this.right===a.right)}},{key:"contains",
value:function(a){return this.isEmpty()?!1:a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom}},{key:"intersect",value:function(a){return this.clone().restrictTo(a)}},{key:"intersects",value:function(a){if(this.isEmpty()||a.isEmpty())return!1;var d=Math.max(this.top,a.top),b=Math.min(this.bottom,a.bottom);return Math.max(this.left,a.left)<Math.min(this.right,a.right)&&d<b}},{key:"toString",value:function(){return"["+this.x+","+this.y+","+this.width+","+this.height+"]"}},
{key:"clone",value:function(){return new c(this.left,this.top,this.right-this.left,this.bottom-this.top)}},{key:"center",value:function(){if(this.isEmpty())throw Error("Empty rectangles do not have centers");return new Ta(this.left+(this.right-this.left)/2,this.top+(this.bottom-this.top)/2)}},{key:"copyFrom",value:function(a){this.top=a.top;this.left=a.left;this.bottom=a.bottom;this.right=a.right;return this}},{key:"setRect",value:function(a,d,b,e){this.left=a;this.top=d;this.right=a+b;this.bottom=
d+e;return this}},{key:"setBounds",value:function(a,d,b,e){this.top=d;this.left=a;this.bottom=e;this.right=b;return this}},{key:"setCenter",value:function(a){this.setBounds(a.left-this.width/2,a.top-this.height/2,a.left+this.width/2,a.top+this.height/2);return this}},{key:"round",value:function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);return this}},{key:"union",value:function(a){return this.clone().expandToContain(a)}},
{key:"translate",value:function(a,d){this.left+=a;this.right+=a;this.top+=d;this.bottom+=d;return this}},{key:"translateInside",value:function(a){var d=0;this.left<=a.left?d=a.left-this.left:this.right>a.right&&(d=a.right-this.right);var b=0;this.top<=a.top?b=a.top-this.top:this.bottom>a.bottom&&(b=a.bottom-this.bottom);return this.translate(d,b)}},{key:"restrictTo",value:function(a){if(this.isEmpty()||a.isEmpty())return this.setRect(0,0,0,0);var d=Math.max(this.left,a.left),b=Math.max(this.top,a.top);
return this.setRect(d,b,Math.max(0,Math.min(this.right,a.right)-d),Math.max(0,Math.min(this.bottom,a.bottom)-b))}},{key:"expandToContain",value:function(a){if(this.isEmpty())return this.copyFrom(a);if(a.isEmpty())return this;var d=Math.min(this.left,a.left),b=Math.min(this.top,a.top);return this.setRect(d,b,Math.max(this.right,a.right)-d,Math.max(this.bottom,a.bottom)-b)}},{key:"map",value:function(a){this.left=a.call(this,this.left);this.top=a.call(this,this.top);this.right=a.call(this,this.right);
this.bottom=a.call(this,this.bottom);return this}},{key:"subtract",value:function(a){var d=new c(0,0,0,0),b=[];a=a.intersect(this);if(a.isEmpty())return[this.clone()];d.setBounds(this.left,this.top,a.left,this.bottom);d.isEmpty()||b.push(d.clone());d.setBounds(a.left,this.top,a.right,a.top);d.isEmpty()||b.push(d.clone());d.setBounds(a.left,a.bottom,a.right,this.bottom);d.isEmpty()||b.push(d.clone());d.setBounds(a.right,this.top,this.right,this.bottom);d.isEmpty()||b.push(d.clone());return b}},{key:"scale",
value:function(a,d){this.left*=a;this.right*=a;this.top*=d;this.bottom*=d;return this}},{key:"blend",value:function(a,d){return new c(this.left+(a.left-this.left)*d,this.top+(a.top-this.top)*d,this.width+(a.width-this.width)*d,this.height+(a.height-this.height)*d)}},{key:"inflate",value:function(a,d){var b=(this.width*a-this.width)/2,e=(this.height*(1<arguments.length?d:a)-this.height)/2;this.left-=b;this.right+=b;this.top-=e;this.bottom+=e;return this}},{key:"inflateFixed",value:function(a){this.left-=
a;this.right+=a;this.top-=a;this.bottom+=a;return this}},{key:"area",value:function(){return this.width*this.height}},{key:"distance",value:function(a){var d={x:0,y:0};this.intersect(a).isEmpty()&&(this.bottom<a.top?d.y=this.bottom-a.top:this.top>a.bottom&&(d.y=this.top-a.bottom),this.right<a.left?d.x=this.right-a.left:this.left>a.right&&(d.x=this.left-a.right));return d}},{key:"snapTo",value:function(a,d){var b=a.center(),e=this.center();"bottom"===d?e.set(b.left,e.top-(this.bottom-a.bottom)):"top"===
d?e.set(b.left,e.top-(this.top-a.top)):"right"===d?e.set(e.left-(this.right-a.right),b.top):"left"===d&&e.set(e.left-(this.left-a.left),b.top);this.setCenter(e)}}],[{key:"fromRect",value:function(a){return new c(a.left,a.top,a.right-a.left,a.bottom-a.top)}}]);return c}();var Y=function(c){function a(b){u(this,a);var e=d.call(this,0,0,0,0);h(q(e),"_el",void 0);h(q(e),"_updateAt",0);h(q(e),"viewbilityStatus",-1);h(q(e),"isInvisible",!1);e._el=b;e.update();return e}J(a,c);var d=Ha(a);v(a,[{key:"update",
value:function(){if(100<=Date.now()-this._updateAt){a.updateViewPort();var b=this._el.getBoundingClientRect();this.setBounds(b.left,b.top,b.right,b.bottom);this._updateAt=Date.now()}}},{key:"viewbility",value:function(){return a.$vp.contains(this)?1:this.area()?a.$vp.clone().restrictTo(this).area()/this.area():0}},{key:"distanceToVp",value:function(){this.update();return this.distance(a.$vp)}}],[{key:"updateViewPort",value:function(){a.$vp.setBounds(0,0,S(),T())}}]);return a}(w);h(Y,"$vp",new w(0,
0,S(),T()));w="object"==typeof self&&self&&self.Object===Object&&self;w="object"==typeof global&&global&&global.Object===Object&&global||w||Function("return this")();var Ua=/\s/,Va=/^\s+/,qa=function(c){var a=typeof c;return null!=c&&("object"==a||"function"==a)};x=w.Symbol;var ra=Object.prototype,Wa=ra.hasOwnProperty,Xa=ra.toString,E=x?x.toStringTag:void 0,Ya=Object.prototype.toString,sa=x?x.toStringTag:void 0,ha=function(c){var a;if(!(a="symbol"==typeof c)&&(a=null!=c&&"object"==typeof c)){if(null==
c)c=void 0===c?"[object Undefined]":"[object Null]";else if(sa&&sa in Object(c)){a=Wa.call(c,E);var d=c[E];try{c[E]=void 0;var b=!0}catch(g){}var e=Xa.call(c);b&&(a?c[E]=d:delete c[E]);c=e}else c=Ya.call(c);a="[object Symbol]"==c}return a},ta=0/0,Za=/^[-+]0x[0-9a-f]+$/i,$a=/^0b[01]+$/i,ab=/^0o[0-7]+$/i,bb=parseInt,ua=function(c){if("number"==typeof c)return c;if(ha(c))return ta;qa(c)&&(c="function"==typeof c.valueOf?c.valueOf():c,c=qa(c)?c+"":c);if("string"!=typeof c)return 0===c?c:+c;if(c){for(var a=
c.slice,d=c.length;d--&&Ua.test(c.charAt(d)););c=a.call(c,0,d+1).replace(Va,"")}return(a=$a.test(c))||ab.test(c)?bb(c.slice(2),a?2:8):Za.test(c)?ta:+c},va=1/0,Ja=Array.isArray,Ka=1/0,ia=(x=x?x.prototype:void 0)?x.toString:void 0,cb=w.isFinite,db=Math.min,La=function(c){var a=Math[c];return function(d,b){d=ua(d);if(null==b)b=0;else{b?(b=ua(b),b=b===va||b===-va?1.7976931348623157E308*(0>b?-1:1):b===b?b:0):b=0===b?b:0;var e=b%1;b=db(b===b?e?b-e:b:0,292)}return b&&cb(d)?(d=((null==d?"":U(d))+"e").split("e"),
d=a(d[0]+"e"+(+d[1]+b)),d=((null==d?"":U(d))+"e").split("e"),+(d[0]+"e"+(+d[1]-b))):a(d)}}("round"),wa={sendBeacon:function(c){var a=new XMLHttpRequest;a.open("GET",c);a.send()}},eb={nonInteraction:"ni",sessionControl:"sc",userId:"uid",hitType:"t",hostname:"dh",page_path:"dp",page_location:"dl",page_title:"dt",page_referrer:"dr",eventCategory:"ec",eventAction:"ea",eventLabel:"el",eventValue:"ev",dimension1:"cd1",dimension2:"cd2",dimension3:"cd3",dimension4:"cd4",dimension5:"cd5",dimension6:"cd6",
dimension7:"cd7",dimension8:"cd8",dimension9:"cd9",dimension10:"cd10",dimension11:"cd11",dimension12:"cd12",dimension13:"cd13",dimension14:"cd14",dimension15:"cd15",dimension16:"cd16",dimension17:"cd17",dimension18:"cd18",dimension19:"cd19",dimension20:"cd20",metric1:"cm1",metric2:"cm2",metric3:"cm3",metric4:"cm4",metric5:"cm5",metric6:"cm6",metric7:"cm7",metric8:"cm8",metric9:"cm9",metric10:"cm10",metric11:"cm11",metric12:"cm12",metric13:"cm13",metric14:"cm14",metric15:"cm15",metric16:"cm16",metric17:"cm17",
metric18:"cm18",metric19:"cm19",metric20:"cm20"},xa=function(){function c(a){var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:"",b=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"";u(this,c);h(this,"_tid","");h(this,"_cid","");h(this,"_url","");h(this,"_createdAt",Date.now());h(this,"_adapter",y(navigator.sendBeacon)?wa:navigator);this._tid=a;this._cid=d;this._url=b||"https://www.google-analytics.com/collect?v=1";window.YMPB.__pvflag[this._tid]||(window.YMPB.__pvflag[this._tid]=
!0,this.pageview())}v(c,[{key:"pageview",value:function(){this.ping("pageview",{})}},{key:"send",value:function(a,d,b,e,g,f){var k=6<arguments.length&&void 0!==arguments[6]?arguments[6]:{};k=k||{};k.eventCategory=b;k.eventAction=e;k.eventLabel=g||"(empty)";k.eventValue=f;k.hasOwnProperty("page_path")||(k.page_path=window.location.pathname);this.ping(d,k)}},{key:"ping",value:function(a,d){if("object"===A(d)){d.hitType=a;d.tid=this._tid;d.cid=this._cid;d.z=Date.now();d.hostname||(d.hostname=window.location.hostname);
d.page_location||(d.page_location=window.location.href);a=this._url;for(var b in d)d.hasOwnProperty(b)&&(a+="&"+(eb[b]||b)+"="+encodeURIComponent("boolean"===typeof d[b]?+d[b]:d[b]));this.sendBeacon(a)}}},{key:"sendBeacon",value:function(a){try{return this._adapter.sendBeacon(a)}catch(d){window.YMPB.__pvflag[this._tid]=!1}}}]);return c}(),fb={nonInteraction:"ni",sessionControl:"sc",userId:"uid",hitType:"t",hostname:"dh",page_path:"page_path",page_location:"dl",page_title:"dt",page_referrer:"dr",eventCategory:"category",
eventAction:"action",eventLabel:"label",eventValue:"value",dimension1:"cd1",dimension2:"cd2",dimension3:"cd3",dimension4:"cd4",dimension5:"cd5",dimension6:"cd6",dimension7:"cd7",dimension8:"cd8",dimension9:"cd9",dimension10:"cd10",dimension11:"cd11",dimension12:"cd12",dimension13:"cd13",dimension14:"cd14",dimension15:"cd15",dimension16:"cd16",dimension17:"cd17",dimension18:"cd18",dimension19:"cd19",dimension20:"cd20",metric1:"cm1",metric2:"cm2",metric3:"cm3",metric4:"cm4",metric5:"cm5",metric6:"cm6",
metric7:"cm7",metric8:"cm8",metric9:"cm9",metric10:"cm10",metric11:"cm11",metric12:"cm12",metric13:"cm13",metric14:"cm14",metric15:"cm15",metric16:"cm16",metric17:"cm17",metric18:"cm18",metric19:"cm19",metric20:"cm20"},ya=function(){function c(a){u(this,c);h(this,"_tid","");h(this,"_uuid","");h(this,"_url","");h(this,"_sessionId","");h(this,"_language","");h(this,"_country","");h(this,"_adapter",y(navigator.sendBeacon)?wa:navigator);h(this,"_options",void 0);this._tid="YollaPing";this._uuid=a.$userSession.get("uuid");
this._url="https://analytics.yollamedia.com:8443/v0/pv?v=1";this._sessionId=a.$userSession.createdAt;this._language=navigator.language;this._options=a;window.YMPB.__pvflag[this._tid]||(window.YMPB.__pvflag[this._tid]=!0,this.pageview())}v(c,[{key:"pageview",value:function(){this.ping("pageview",{action:"pageview",label:"pageview",category:"pageview",value:1})}},{key:"send",value:function(a,d,b,e,g,f,k){k=k||{};k.eventCategory=b;k.eventAction=e;k.eventLabel=g||"(empty)";k.eventValue=f;k.hasOwnProperty("page_path")||
(k.page_path=window.location.pathname);this.ping(d,k)}},{key:"ping",value:function(a,d){if("object"===A(d)&&a){d=d||{};d.type=a;d.uuid=this._uuid;d.session_id=this._sessionId;d.language=this._language;d.country=this._options.$geoInfo.values.countryCode?this._options.$geoInfo.values.countryCode:"unknown";d.browser_size="".concat(S(),"x").concat(T());d.domain_id=this._options.getOption("DOMAIN_ID");d.ts=Date.now();d.hostname||(d.hostname=window.location.hostname);d.page_location||(d.page_location=window.location.href);
a=this._url;for(var b in d)d.hasOwnProperty(b)&&(a+="&"+(fb[b]||b)+"="+encodeURIComponent("boolean"===typeof d[b]?+d[b]:d[b]));this.sendBeacon(a)}}},{key:"sendBeacon",value:function(a){try{return this._adapter.sendBeacon(a)}catch(d){window.YMPB.__pvflag[this._tid]=!1}}}]);return c}();w=function(c){function a(b){u(this,a);var e=d.call(this);h(q(e),"_tagUrl",null);h(q(e),"_config",void 0);h(q(e),"$variantCases",void 0);h(q(e),"$deviceDetector",void 0);h(q(e),"$sessionStorage",void 0);h(q(e),"$userSession",
void 0);h(q(e),"$geoInfo",void 0);h(q(e),"loadGeoInfoTracker",function(f,k){var n=e.getOption("DIAGNOSIS_GA_ACCOUNT")||"UA-125030536-7",p=e.$userSession.get("uuid");n=new xa(n,p);p=new ya(q(e));var r=e.getOption("YMPB_PRELOAD_VERSION");n.send("ytt.send","event","Preload"+r,f,k,k);p.send("ytt.send","event","Preload"+r,f,k,k,{})});e._config=b;b.DFP_CHILD_NETWORK&&(e._config.DFP_NETWORK+=",".concat(b.DFP_CHILD_NETWORK));try{var g=window.sessionStorage}catch(f){g=new R}e.$sessionStorage=new W(g,"YMPB_OPTIONS");
e.$deviceDetector=new Pa;e.$variantCases=new pa;e.$userSession=new Sa;e.$geoInfo=new oa(fa(),"YMPB_OPTIONS",{key:"_GEO",ttl:172800});return e}J(a,c);var d=Na(a);v(a,[{key:"version",get:function(){if("string"===typeof this.tagUrl){var b=this.tagUrl.match(/(\d+(\.\d+)+)/);if(b)return b[0]}return null}},{key:"tagUrl",get:function(){return this._tagUrl}},{key:"buildTagUrlByVersion",value:function(b){return a.isValidTagUrl(b)?b:a.isValidTagVersion(b)?M.combineURLs("https://portal.cdn.yollamedia.com/storage/tpl/",
[b,"ympb.js"].join("/")):null}},{key:"init",value:function(b){var e=this;this.$userSession.isValid()?this.$variantCases.activityCaseIndex=this.$userSession.values.name:this.$userSession.createSession(this.$variantCases.randomlySetCase());var g=this.$sessionStorage.get("VERSION");"string"!==typeof g&&(g="");a.isValidTagUrl(g)?this._tagUrl=g:this._tagUrl=this.buildTagUrlByVersion(this.$variantCases.activityCase.version);this.$geoInfo.isValid()?(this.resetVariantCase(this.$variantCases.activityCaseIndex),
b&&b()):this.loadGeoInfo(function(f,k){if(!f){e.setOption("TCF_VERSION","2.0");var n=e.getOption("YMPB_GDPR_UI_LAYOUT");n&&!/\.\w+$/.test(n)&&e.setOption("YMPB_GDPR_UI_LAYOUT","")}e.resetVariantCase(e.$variantCases.activityCaseIndex);b&&b({geoDataLoaded:f,time:k})})}},{key:"loadGeoInfo",value:function(b){var e=this,g=new Qa({baseUrl:"https://portal.cdn.yollamedia.com"}),f=Date.now(),k=this.getOption("YMPB_PRELOAD_VERSION"),n="/storage/tpl/yolla_preload.json";k&&(n=n.replace(/(\.json)$/,k+"$1"));g.get({url:n,
async:!0,mimeType:"application/json",headers:{Accept:"application/json;charset=UTF-8"},timout:this.getOption("YMPB_PRELOAD_TIMEOUT"),requestTracker:this.loadGeoInfoTracker},function(p){var r=!1,F=Date.now()-f;if(200===p.status)try{var G=JSON.parse(p.data);e.$geoInfo.create(G);r=!0}catch(D){}b&&b(r,F)},function(){var p=Date.now()-f;b&&b(!1,p)})}},{key:"setOption",value:function(b,e){var g=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!1;this.setOptions(h({},b,e),g)}},{key:"setOptions",value:function(b){var e=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,g;for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(Object.prototype.hasOwnProperty.call(L,g)||delete b[g]);if(!P(b))if(this._store=Object.assign({},this._store,b),e)e=this.$sessionStorage.get("OPTIONS")||{},e=Object.assign({},e,b),this.$sessionStorage.set("OPTIONS",e);else for(var f in b)this._config[f]=b[f]}},{key:"getOption",value:function(b){return Object.prototype.hasOwnProperty.call(this._store,b)?this._store[b]:Object.prototype.hasOwnProperty.call(this._config,
b)?this._config[b]:L[b]}},{key:"getOptions",value:function(){return this._store}},{key:"resetVariantCase",value:function(b,e,g){var f,k=this,n=this.$sessionStorage.get("OPTIONS")||{};e?e!==this.$deviceDetector.deviceType&&(this.$deviceDetector.deviceType=e):e=this.$deviceDetector.deviceType;g||=n.REGIONAL_CODE?n.REGIONAL_CODE:this.$geoInfo.isValid()?this.$geoInfo.values.countryCode:"";b=this.$variantCases.getMacroOptionsByIndex(b,this.$deviceDetector.deviceType,g);b.YMPB_VARIANT&&(b.YMPB_EVENT_CATEGORY=
b.YMPB_VARIANT+"");b.DEBUG&&(b.ENABLE_ANALYTICS=!1);b.UUID=this.$userSession.uuid;g={REGIONAL_CODE:g,GDPR_ENABLED:null===(f=this.$geoInfo.values)||void 0===f?void 0:f.is_gdpr};f=Object.assign({},L,g,b,window.YMPB_DATA||{},n,this._config);if(f.ENABLE_S2S&&f.S2S_CONFIG&&f.S2S_CONFIG.bidders){n=Object.assign({},Ra);n.timeout=Math.round(.8*f.YMPB_AUCTION_TIMEOUT);n.bidders=f.S2S_CONFIG.bidders.slice();n.bidderControl=n.bidderControl||{};for(var p in f.S2S_CONFIG.bidders)Object.prototype.hasOwnProperty.call(f.S2S_CONFIG.bidders,
p)&&(n.bidderControl[p]=n.bidderControl[p]||{},n.bidderControl[p].includeSourceKvp=!0);n.extPrebid={aliases:{}};f.S2S_CONFIG=n}if(0>f.YMPB_PB_REDUCE||1<f.YMPB_PB_REDUCE)f.YMPB_PB_REDUCE=0;f.YMPB_PUBLISHER_ID||(f.YMPB_PUBLISHER_ID=f.SCHAIN_ID);f.YMPB_FORCE_QUANTCAST&&(f.GDPR_ENABLED=!0);"2.1"!==f.TCF_VERSION&&(f.TCF_VERSION="2.0");f.GDPR_ENABLED?!1===f.YMPB_GDPR_UI&&(f.TCF_VERSION="2.1"):y(f.GDPR_ENABLED)&&"2.0"===f.TCF_VERSION&&(f.GDPR_ENABLED=!0);if(f.CHECKING_BETTER_ADS){var r;f.CHECKING_BETTER_ADS=
null===(r=this.$geoInfo.values)||void 0===r?void 0:r.is_better_ads}this._store=f;this.$deviceDetector.resetSlotType(this);window.googletag.cmd.push(function(){k.setGtpTrackTargeting()})}},{key:"switchToVersion",value:function(b){if(b=this.buildTagUrlByVersion(b))this.$sessionStorage.set("VERSION",b),b!==this.tagUrl&&window.location.reload()}},{key:"switchToCase",value:function(b){var e=this.$variantCases.activityCaseIndex;this.$variantCases.activityCaseIndex=b;e!==this.$variantCases.activityCaseIndex&&
(this.$userSession.set("name",this.$variantCases.activityCaseIndex),this.$userSession.update(),window.location.reload())}},{key:"find",value:function(b,e){b=this.getOption(b);if(!y(b))return y(e)?b:b&&Array.isArray(b)?"function"===typeof e?b.findIndex(e):b.indexOf(e):C(b,"Object")&&C(e,"String")?ea(b,e):e===b?b:void 0}},{key:"getTrackingValues",value:function(){var b=this.getOption("YMPB_OPTION_TRACKING"),e={},g;for(g in b)if(Object.prototype.hasOwnProperty.call(b,g)){var f=b[g].split("=");if(2===
f.length&&!P(f[0])){var k=this.getOption(g);switch(f[1].toUpperCase()){case "%VALUE%":e[f[0]]=y(k)?"":k;break;case "%STATUS%":e[f[0]]=k&&0<k?1:0;break;default:y(k)||P(f[1])||(e[f[0]]=f[1])}}}b=[Y.$vp.width,Y.$vp.height];b[0]=400>b[0]?"NARROW":1400<b[0]?"WIDE":ja(+b[0],50);b[1]=400>b[1]?"SHORT":1E3<b[1]?"TALL":ja(+b[1],50);b=b.join("x");e.scrnsz=b;if(b=Ma("ytest"))e.ytest=b;e.ypreload=this.$geoInfo.createdAt?"success":"fail";return e}},{key:"setGtpTrackTargeting",value:function(){window.googletag.pubads().clearTargeting();
var b=this.getTrackingValues(),e;for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&window.googletag.pubads().setTargeting(e,b[e]+"")}}],[{key:"isValidTagVersion",value:function(b){return b?/^\d+(\.\d+)+$/.test(b):!1}},{key:"isValidTagUrl",value:function(b){return b&&M.isAbsoluteURL(b)?/\/ympb\.js(\?.*)?$/i.test(b):!1}}]);return a}(R);x=function(){function c(){u(this,c);h(this,"delegate",document.createDocumentFragment())}v(c,[{key:"addEventListener",value:function(){for(var a=arguments.length,
d=Array(a),b=0;b<a;b++)d[b]=arguments[b];this.delegate.addEventListener.apply(this.delegate,d)}},{key:"dispatchEvent",value:function(){for(var a=arguments.length,d=Array(a),b=0;b<a;b++)d[b]=arguments[b];return this.delegate.dispatchEvent.apply(this.delegate,d)}},{key:"removeEventListener",value:function(){for(var a=arguments.length,d=Array(a),b=0;b<a;b++)d[b]=arguments[b];return this.delegate.removeEventListener.apply(this.delegate,d)}},{key:"destroy",value:function(){this.delegate=null}}]);return c}();
new x;window.googletag=window.googletag||{};window.googletag.cmd=window.googletag.cmd||[];window._qevents=window._qevents||[];var l={que:[]};window.YMPB?l=window.YMPB:window.YMPB=l;window.YMPB_DATA=window.YMPB_DATA||{};window.YMPB_OPTIONS=window.YMPB_OPTIONS||{};window.YMPB.__pvflag={};l.ycmd=l.ycmd||l.command||[];l.command=l.ycmd||[];var Z=new x;l.addEventListener=function(c,a){Z.addEventListener(c,a)};l.removeEventListener=function(c,a){Z.removeEventListener(c,a)};l.dispatchEvent=function(c){Z.dispatchEvent(c)};
try{window.YMPB_DATA={YMPB_PRELOAD_TIMEOUT:1500,YMPB_PRELOAD_VERSION:"_v2"},l=l||{},l.que=l.que||[],function(c){function a(){for(var b=!1,e=document.querySelectorAll(".ympb_custom"),g=window.innerHeight,f=function(H,aa){H=H.split(",");for(var za=!0,ba=0;ba<H.length;ba++){var I=(H[ba]||"").split("-");I.length&&(za=1===I.length?aa>=I[0]:aa>=I[0]&&aa<=I[1])}return za},k=0;k<e.length;k++){var n=e[k],p=n.offsetWidth;n=n.querySelectorAll(".ympb_group");for(var r=0;r<n.length;r++){var F=!0,G=!0,D=n[r],Aa=
D.dataset.adwidth,Ba=D.dataset.adheight,gb=D.style.display;Ba&&(F=f(Ba,g));Aa&&(G=f(Aa,p));try{D.style.setProperty("display",F&&G?"block":"none","important")}catch(H){D.style.display=F&&G?"block":"none"}gb!==D.style.display&&(b=!0)}}b&&(window.scrollTo(window.pageXOffset,window.pageYOffset-1),window.scrollTo(window.pageXOffset,window.pageYOffset+1))}var d=function(b,e){var g=null;return function(){var f=this,k=arguments;clearTimeout(g);g=setTimeout(function(){b.apply(f,k)},e)}}(a,500);c.que.push(function(){a();
d();window.addEventListener("resize",d)})}(l)}catch(c){window.console.error(c)}var m=new w({DOMAIN_ID:30,DFP_NETWORK:21745415141,DFP_CHILD_NETWORK:"3988370",DFP_PUBLISHER_UNIT:"iogames.space",GA_SITE_ID:"UA-77565304-1",SCHAIN_ID:"eff5d42a7fdd54036ccf9a99a729e8c7",BIDSADJUSTMENT:{appnexus:{bidCpmAdjustment:function(c){return.98*c}},appnexus_v:{bidCpmAdjustment:function(c){return.98*c}},rubicon:{bidCpmAdjustment:function(c){return.7987588*c}},ix:{bidCpmAdjustment:function(c){return.94*c}},triplelift:{bidCpmAdjustment:function(c){return.9604*
c}},"33across":{bidCpmAdjustment:function(c){return.96*c}},openx:{bidCpmAdjustment:function(c){return.96*c}},pulsepoint:{bidCpmAdjustment:function(c){return.96*c}},openx_v:{bidCpmAdjustment:function(c){return.96*c}},appnexus_v2:{bidCpmAdjustment:function(c){return.98*c}}},YMPB_TEMPLATE_CSS:'[id^="ympb_wrapper__desktop-leaderboard"] {\n    height: 90px !important;\n    overflow: visible;\n}\n\n[id^="ympb_sizer__desktop-leaderboard"] {\n    height: 90px !important;\n    overflow: hidden !important;\n}\n/*\n.AdContainer .ympb_target_banner {\n    min-width: 336px;\n}\n*/',
YMPB_OPTION_TRACKING:{YMPB_VARIANT:"yvariant=%VALUE%"},YMPB_TEMPLATE_CDN:"https://portal.cdn.yollamedia.com",YMPB_CMP_VENDORLIST:"https://portal.cdn.yollamedia.com/storage/consent/e54575a7316d8e758557af734aca7c6b.json"});0<window.YMPB_DATA.YMPB_PRELOAD_TIMEOUT&&m.setOption("YMPB_PRELOAD_TIMEOUT",window.YMPB_DATA.YMPB_PRELOAD_TIMEOUT);window.YMPB_DATA.YMPB_PRELOAD_VERSION&&m.setOption("YMPB_PRELOAD_VERSION",window.YMPB_DATA.YMPB_PRELOAD_VERSION);m.$variantCases.init({desktop:{YMPB_VARIANT:"",YMPB_VARIANT_NOTES:"",
GA_ACCOUNT:"",CROSS_DOMAIN_GA_ACCOUNT:"",GA_CLIENT_TYPE:"auto",YMPB_GDPR_UI:!0,GDPR_LAYOUT:"vertical",TCF_VERSION:"2.0",QUANTCAST_HOSTNAME:"",YMPB_FORCE_QUANTCAST:!1,YMPB_GDPR_UI_LAYOUT:"",YMPB_USP_UI:!0,YMPB_USP_CONTAINER:"",USE_PARENT_TCF:!1,YMPB_AUCTION_TIMEOUT:1500,BIDDERS:[],BIDDER_LABELS_INITING:[],YMPB_ENABLE_ADDITIONAL_BIDS:0,BIDDER_LABELS_INITCACHING:[],YMPB_REFRESHRATE_MIN:30,YMPB_DEFAULT_REFRESHRATE:30,REFRESHRATE_ONE_LIMIT:0,YMPB_REFRESHRATE_TWO:0,REFRESHRATE_TWO_LIMIT:0,YMPB_REFRESHRATE_THREE:0,
REFRESHRATE_THREE_LIMIT:0,YMPB_REFRESH_RATE_NOFILL:0,YMPB_FORCE_REFRESH_ACTIVE:0,YMPB_FORCE_REFRESH:0,YMPB_DESTROY_BEFORE_REFRESH:!0,YMPB_REFRESH_UNVIEWED:!1,YMPB_REFRESH_NOT_INVIEW:!1,REFRESH_VISIBLE_FROM_HIDDEN:!1,YMPB_REFRESH_BATCH:0,YMPB_REFRESH_ON_RESIZE:!1,BIDDER_LABELS_REFRESHING:[],YMPB_BID_CACHE_MIN_TTL_OVERRIDE:1,YMPB_BID_CACHE_TTL:180,YMPB_ENABLE_CACHE:{banner:!0,native:!0,video:!0},YMPB_PRECACHE_MAX_BIDS:45,YMPB_MAX_CACHE:100,YMPB_CACHE_STORAGE_SIZE:0,YMPB_FILTER_MIN_CPM:0,BIDDER_LABELS_PRECACHING:[],
YMPB_PRECACHE_INTERVAL:5,YMPB_PRECACHE_MULTIPLIER:1,BIDDER_LABELS_PRECACHING_2:[],YMPB_PRECACHE_INTERVAL_2:60,YMPB_PRECACHE_MULTIPLIER_2:1,YMPB_PRECACHE_MODE:"standard",YMPB_PRECACHE_BATCH:5,YMPB_PRECACHE_GREEDY:!1,YMPB_ENABLE_SWAPPING:!0,SWAPPING_INTERVAL:3,SWAP_IGNORE_BIDDERS:[],REFRESH_IGNORE_VIEW_STATUS:[],REFRESH_IGNORE_ADX_VIEW_STATUS:!0,YMPB_AUTO_INSERT:[],YMPB_TABLET_SLOTS:"desktop",YMPB_BASE_INDEX:"2147483548",YMPB_VIDEO_AUTOPLAY:!1,PREROLL_WIDTH:100,YMPB_VIDEO_VOLUME:0,YMPB_VIDEO_SKIP_TIMER:30,
PREROLL_CONFIG:{maxduration:30},GAM_VIDEO_CONIFG:{},YMPB_VIDEO_TIMEOUT:10,YMPB_VIDEO_FULLSCREEN:!1,YMPB_VIDEO_LOGO:!0,YMPB_VIDEO_SFLOOR:.05,PREROLL_RETRY:1,PREROLL_RESPONSIVE:!1,PREROLL_ASPECT_RATIO:0,ENABLE_DISPLAY_IN_PREROLL:4,EMBEDDED_URL_HOST_ONLY:!1,ENABLE_SEND_ALL_VIDEO_BIDS:!0,YMPB_VIDEO_BID_MIN_TTL:180,YMPB_VIDEO_BID_MAX_TTL:600,DYNAMIC_LOAD_SCREEN_VH:2,DYNAMIC_LOAD_SCREEN_VH_ABOVE:2,DYNAMIC_LOAD_SPEED_LIMIT:.5,DYNAMIC_DESTROY_VIEWED:!0,YMPB_AD_FOOTER_ENABLED:!1,YMPB_AD_FOOTER_TEXT_TO_ALL:!1,
YMPB_AD_FOOTER_TEXT:"",ADHESION_ENABLECLOSE:!1,ADHESION_BG_COLOR:"",YMPB_SINGLE_REQUEST:!0,ENABLE_SEND_ALL_BIDS:!0,DISABLE_AJAX_TIMEOUT:!1,CHECKING_BETTER_ADS:!0,DYNAMIC_DESTROY:!0,ENABLE_S2S:!0,ENABLE_ADSENCE_PASSBACK:!1,BIDDER_LABELS_PREFETCHING:[],YMPB_USE_CACHE_POSTAUCTION:!1,YMPB_SFLOOR:.05,YMPB_PB_REDUCE:.01,YMPB_REFRSH_UNVIEWED_WITH_LV:!0,YMPB_COLLAPSE_DYNAMIC_ABOVE:!0,YMPB_COLLAPSE_WITH_PLACEHOLDER:!0,CHILD_DIRECTED_TREATMENT:!1,YMPB_ENABLE_BLOCKTHROUGH:!1,YMPB_ENABLE_WITH_BLOCKER:!1,YMPB_ENABLE_CLEANIO_SCRIPT:!1,
YMPB_WRAPPER_MAX_HEIGHT:!1,YMPB_WRAPPER_LEADER_MAX_HEIGHT:!1,YMPB_CACHE_SP_LOGIC:!1,YMPB_CACHE_SP_THRESHOLD:.75,YMPB_CACHE_SP_TTL_BUFFER:10,ENUM_SCHAIN_VALIDATION:"strict",YMPB_PUBLISHER_ID:"",YMPB_ENABLE_FLUID_SIZE:!1,YMPB_ENABLE_SMALLER_SIZE:!1,MAX_SLOTS:99,YMPB_USE_CONTAINER_SIZE:!1,DELAY:0,MAX_DELAY:0,YMPB_USE_RAF_API:!0,YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0,YMPB_LEADERBOARD_TO_MULTI:{},YMPB_LEADERBOARD_TO_MULTI_NUM:{},BIDDER_LABELS_IGNORE_ON_MULTI:["triplelift"],ENABLE_USER_SYNC:!0,
USER_SYNC_FILTER:{iframe:{bidders:"*",filter:"include"}},YMPB_NOT_RUN_CHECKER:"body.ympb_no_ads",YMPB_CUSTOM_CSS:"",YMPB_CUSTOM_JS:null,ENABLE_NATIVE:!1,ENABLE_INTERSTITIAL:!1,RENDER_NOFILL:!0,EMBEDDED_URL_TAIL_SLASH:!1,ENABLE_CUSTOM_TRACKER:!1,SWAP_OVERLAP:.5,SWAP_SIZE_ON_INIT:!1,YMPB_ENABLE_FLUID_FROM_AUTOSIZE:!1}});m.$variantCases.addCases([{weight:5,is_main:!0,version:"3.3.0.33",macro_options:{desktop:{YMPB_AD_FOOTER_TEXT:"powered by <b>Yolla</b>",ADHESION_ENABLECLOSE:!1,BIDDERS:"33across appnexus appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),
YMPB_VARIANT:"59",ENABLE_ADSENCE_PASSBACK:!1,BIDDER_LABELS_INITING:"33across appnexus appnexus_v appnexus_v2 districtm_v ix openx openx_v pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_PRECACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_REFRESHING:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_INITCACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),ADHESION_BG_COLOR:"rgba(64, 68, 81,0.7)",
YMPB_REFRESHRATE_MIN:15,YMPB_REFRESH_UNVIEWED:!0,YMPB_REFRESH_NOT_INVIEW:!0,YMPB_REFRESH_RATE_NOFILL:60,REFRESH_IGNORE_ADX_VIEW_STATUS:!1,YMPB_PRECACHE_MAX_BIDS:200,YMPB_FILTER_MIN_CPM:.07,YMPB_BID_CACHE_MIN_TTL_OVERRIDE:300,YMPB_BID_CACHE_TTL:15E3,YMPB_PRECACHE_INTERVAL:0,SWAPPING_INTERVAL:3,YMPB_VIDEO_AUTOPLAY:!0,YMPB_VIDEO_VOLUME:100,YMPB_VIDEO_SKIP_TIMER:30,YMPB_VIDEO_TIMEOUT:10,DYNAMIC_LOAD_SCREEN_VH:4,DYNAMIC_LOAD_SCREEN_VH_ABOVE:5,DYNAMIC_DESTROY_VIEWED:!1,YMPB_AUCTION_TIMEOUT:4E3,DISABLE_AJAX_TIMEOUT:!0,
CHECKING_BETTER_ADS:!1,ENABLE_S2S:!1,YMPB_ENABLE_ADDITIONAL_BIDS:3,YMPB_USE_CACHE_POSTAUCTION:!0,YMPB_REFRSH_UNVIEWED_WITH_LV:!1,YMPB_COLLAPSE_DYNAMIC_ABOVE:!1,YMPB_ENABLE_BLOCKTHROUGH:!0,YMPB_ENABLE_WITH_BLOCKER:!0,YMPB_CACHE_SP_THRESHOLD:.75,ENUM_SCHAIN_VALIDATION:"strict",YMPB_PUBLISHER_ID:"",YMPB_ENABLE_FLUID_SIZE:!0,YMPB_ENABLE_SMALLER_SIZE:!0,YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0,USER_SYNC_FILTER:{iframe:{bidders:"*",filter:"include"}},YMPB_USP_CONTAINER:"#ymbp_usp_iogames_next",
YMPB_BASE_INDEX:"99998",YMPB_CUSTOM_CSS:'ins[data-google-query-id]::before {\n    content: "\\00d7";\n    display: block;\n    width: 48px;\n    height: 48px;\n    position: absolute;\n    right: 20px;\n    top:0;\n    z-index: 1;\n    font-size: 38px;\n    color: #ccc;\n    text-shadow: 0px 0px 1px #000;\n    pointer-events: none;\n}',YMPB_CUSTOM_JS:null,REFRESH_IGNORE_VIEW_STATUS:["triplelift"],SWAP_IGNORE_BIDDERS:["triplelift"],YMPB_VARIANT_NOTES:"Updated refresh settings",ENABLE_INTERSTITIAL:!0,
PREROLL_RETRY:1,YMPB_FORCE_REFRESH:0,GA_ACCOUNT:"UA-77565304-1",REFRESHRATE_ONE_LIMIT:100,YMPB_REFRESHRATE_TWO:15,REFRESHRATE_TWO_LIMIT:100,YMPB_REFRESHRATE_THREE:60,YMPB_FORCE_REFRESH_ACTIVE:240},mobile:{YMPB_ENABLE_FLUID_SIZE:!1,YMPB_CUSTOM_CSS:"",YMPB_ENABLE_SWAPPING:!1,ENABLE_INTERSTITIAL:!1},tablet:{}},geo_target_options:{US:{desktop:{YMPB_MEDREC_TO_MULTI:{multiMode:"dynamic",slotSpacing:20,maxSize:"0x250",maxSlots:2},YMPB_MEDREC_TO_MULTI_NUM:2},mobile:{YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0},
tablet:{}}},case_control:!1,variant_template_id:0},{weight:65,is_main:!1,version:"3.3.0.8.2",macro_options:{desktop:{YMPB_AD_FOOTER_TEXT:"powered by <b>Yolla</b>",ADHESION_ENABLECLOSE:!1,BIDDERS:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),YMPB_VARIANT:"60",ENABLE_ADSENCE_PASSBACK:!1,BIDDER_LABELS_INITING:"33across appnexus appnexus_v appnexus_v2 districtm_v ix openx openx_v pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_PRECACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),
BIDDER_LABELS_REFRESHING:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_INITCACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),ADHESION_BG_COLOR:"rgba(64, 68, 81,0.7)",YMPB_REFRESHRATE_MIN:25,YMPB_REFRESH_UNVIEWED:!0,YMPB_REFRESH_NOT_INVIEW:!0,YMPB_REFRESH_RATE_NOFILL:60,REFRESH_IGNORE_ADX_VIEW_STATUS:!1,YMPB_PRECACHE_MAX_BIDS:200,YMPB_FILTER_MIN_CPM:.07,YMPB_BID_CACHE_MIN_TTL_OVERRIDE:300,YMPB_BID_CACHE_TTL:900,
YMPB_PRECACHE_INTERVAL:900,SWAPPING_INTERVAL:3,YMPB_VIDEO_AUTOPLAY:!0,YMPB_VIDEO_VOLUME:100,YMPB_VIDEO_SKIP_TIMER:30,YMPB_VIDEO_TIMEOUT:10,DYNAMIC_LOAD_SCREEN_VH:4,DYNAMIC_LOAD_SCREEN_VH_ABOVE:5,DYNAMIC_DESTROY_VIEWED:!1,YMPB_AUCTION_TIMEOUT:2E3,DISABLE_AJAX_TIMEOUT:!0,CHECKING_BETTER_ADS:!1,ENABLE_S2S:!1,YMPB_ENABLE_ADDITIONAL_BIDS:3,YMPB_USE_CACHE_POSTAUCTION:!0,YMPB_REFRSH_UNVIEWED_WITH_LV:!1,YMPB_COLLAPSE_DYNAMIC_ABOVE:!1,YMPB_ENABLE_BLOCKTHROUGH:!0,YMPB_ENABLE_WITH_BLOCKER:!0,YMPB_CACHE_SP_THRESHOLD:.75,
ENUM_SCHAIN_VALIDATION:"strict",YMPB_PUBLISHER_ID:"",YMPB_ENABLE_FLUID_SIZE:!0,YMPB_ENABLE_SMALLER_SIZE:!0,YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0,USER_SYNC_FILTER:{iframe:{bidders:"*",filter:"include"}},YMPB_USP_CONTAINER:"#ymbp_usp_iogames_next",YMPB_BASE_INDEX:"99998",YMPB_CUSTOM_CSS:'ins[data-google-query-id]::before {\n    content: "\\00d7";\n    display: block;\n    width: 48px;\n    height: 48px;\n    position: absolute;\n    right: 20px;\n    top:0;\n    z-index: 1;\n    font-size: 38px;\n    color: #ccc;\n    text-shadow: 0px 0px 1px #000;\n    pointer-events: none;\n}',
YMPB_CUSTOM_JS:null,REFRESH_IGNORE_VIEW_STATUS:["triplelift"],SWAP_IGNORE_BIDDERS:["triplelift"],YMPB_VARIANT_NOTES:"",ENABLE_INTERSTITIAL:!0,PREROLL_RETRY:1,YMPB_FORCE_REFRESH:240,GA_ACCOUNT:"UA-77565304-1"},mobile:{YMPB_ENABLE_FLUID_SIZE:!1,YMPB_CUSTOM_CSS:"",YMPB_ENABLE_SWAPPING:!1,ENABLE_INTERSTITIAL:!1},tablet:{}},geo_target_options:{US:{desktop:{YMPB_DEFAULT_REFRESHRATE:26,YMPB_MEDREC_TO_MULTI:{multiMode:"dynamic",slotSpacing:20,maxSize:"0x250",maxSlots:2},YMPB_MEDREC_TO_MULTI_NUM:2},mobile:{YMPB_MEDREC_TO_MULTI:{},
YMPB_MEDREC_TO_MULTI_NUM:0},tablet:{}}},case_control:!0,variant_template_id:0},{weight:10,is_main:!1,version:"3.3.0.20",macro_options:{desktop:{YMPB_AD_FOOTER_TEXT:"powered by <b>Yolla</b>",ADHESION_ENABLECLOSE:!1,BIDDERS:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),YMPB_VARIANT:"61",ENABLE_ADSENCE_PASSBACK:!1,BIDDER_LABELS_INITING:"33across appnexus appnexus_v appnexus_v2 districtm_v ix openx openx_v pulsepoint rubicon triplelift".split(" "),
BIDDER_LABELS_PRECACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_REFRESHING:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_INITCACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),ADHESION_BG_COLOR:"rgba(64, 68, 81,0.7)",YMPB_REFRESHRATE_MIN:25,YMPB_REFRESH_UNVIEWED:!0,YMPB_REFRESH_NOT_INVIEW:!0,YMPB_REFRESH_RATE_NOFILL:60,REFRESH_IGNORE_ADX_VIEW_STATUS:!1,YMPB_PRECACHE_MAX_BIDS:200,
YMPB_FILTER_MIN_CPM:.07,YMPB_BID_CACHE_MIN_TTL_OVERRIDE:300,YMPB_BID_CACHE_TTL:900,YMPB_PRECACHE_INTERVAL:900,SWAPPING_INTERVAL:3,YMPB_VIDEO_AUTOPLAY:!0,YMPB_VIDEO_VOLUME:100,YMPB_VIDEO_SKIP_TIMER:30,YMPB_VIDEO_TIMEOUT:10,DYNAMIC_LOAD_SCREEN_VH:4,DYNAMIC_LOAD_SCREEN_VH_ABOVE:5,DYNAMIC_DESTROY_VIEWED:!1,YMPB_AUCTION_TIMEOUT:3E3,DISABLE_AJAX_TIMEOUT:!0,CHECKING_BETTER_ADS:!1,ENABLE_S2S:!1,YMPB_ENABLE_ADDITIONAL_BIDS:3,YMPB_USE_CACHE_POSTAUCTION:!0,YMPB_REFRSH_UNVIEWED_WITH_LV:!1,YMPB_COLLAPSE_DYNAMIC_ABOVE:!1,
YMPB_ENABLE_BLOCKTHROUGH:!0,YMPB_ENABLE_WITH_BLOCKER:!0,YMPB_CACHE_SP_THRESHOLD:.75,ENUM_SCHAIN_VALIDATION:"strict",YMPB_PUBLISHER_ID:"",YMPB_ENABLE_FLUID_SIZE:!0,YMPB_ENABLE_SMALLER_SIZE:!0,YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0,USER_SYNC_FILTER:{iframe:{bidders:"*",filter:"include"}},YMPB_USP_CONTAINER:"#ymbp_usp_iogames_next",YMPB_BASE_INDEX:"99998",YMPB_CUSTOM_CSS:'ins[data-google-query-id]::before {\n    content: "\\00d7";\n    display: block;\n    width: 48px;\n    height: 48px;\n    position: absolute;\n    right: 20px;\n    top:0;\n    z-index: 1;\n    font-size: 38px;\n    color: #ccc;\n    text-shadow: 0px 0px 1px #000;\n    pointer-events: none;\n}',
YMPB_CUSTOM_JS:null,REFRESH_IGNORE_VIEW_STATUS:["triplelift"],SWAP_IGNORE_BIDDERS:["triplelift"],YMPB_VARIANT_NOTES:"Timeout 3000, refresh rate 30",ENABLE_INTERSTITIAL:!0,PREROLL_RETRY:1,YMPB_FORCE_REFRESH:240,GA_ACCOUNT:"UA-77565304-1"},mobile:{YMPB_ENABLE_FLUID_SIZE:!1,YMPB_CUSTOM_CSS:"",YMPB_ENABLE_SWAPPING:!1,ENABLE_INTERSTITIAL:!1},tablet:{}},geo_target_options:{US:{desktop:{YMPB_MEDREC_TO_MULTI:{multiMode:"dynamic",slotSpacing:20,maxSize:"0x250",maxSlots:2},YMPB_MEDREC_TO_MULTI_NUM:2},mobile:{YMPB_MEDREC_TO_MULTI:{},
YMPB_MEDREC_TO_MULTI_NUM:0},tablet:{}}},case_control:!1,variant_template_id:0},{weight:10,is_main:!1,version:"3.3.0.20",macro_options:{desktop:{YMPB_AD_FOOTER_TEXT:"powered by <b>Yolla</b>",ADHESION_ENABLECLOSE:!1,BIDDERS:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),YMPB_VARIANT:"62",ENABLE_ADSENCE_PASSBACK:!1,BIDDER_LABELS_INITING:"33across appnexus appnexus_v appnexus_v2 districtm_v ix openx openx_v pulsepoint rubicon triplelift".split(" "),
BIDDER_LABELS_PRECACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_REFRESHING:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_INITCACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),ADHESION_BG_COLOR:"rgba(64, 68, 81,0.7)",YMPB_REFRESHRATE_MIN:25,YMPB_REFRESH_UNVIEWED:!0,YMPB_REFRESH_NOT_INVIEW:!0,YMPB_REFRESH_RATE_NOFILL:60,REFRESH_IGNORE_ADX_VIEW_STATUS:!1,YMPB_PRECACHE_MAX_BIDS:200,
YMPB_FILTER_MIN_CPM:.07,YMPB_BID_CACHE_MIN_TTL_OVERRIDE:300,YMPB_BID_CACHE_TTL:900,YMPB_PRECACHE_INTERVAL:900,SWAPPING_INTERVAL:3,YMPB_VIDEO_AUTOPLAY:!0,YMPB_VIDEO_VOLUME:100,YMPB_VIDEO_SKIP_TIMER:30,YMPB_VIDEO_TIMEOUT:10,DYNAMIC_LOAD_SCREEN_VH:4,DYNAMIC_LOAD_SCREEN_VH_ABOVE:5,DYNAMIC_DESTROY_VIEWED:!1,YMPB_AUCTION_TIMEOUT:3E3,DISABLE_AJAX_TIMEOUT:!0,CHECKING_BETTER_ADS:!1,ENABLE_S2S:!1,YMPB_ENABLE_ADDITIONAL_BIDS:3,YMPB_USE_CACHE_POSTAUCTION:!0,YMPB_REFRSH_UNVIEWED_WITH_LV:!1,YMPB_COLLAPSE_DYNAMIC_ABOVE:!1,
YMPB_ENABLE_BLOCKTHROUGH:!0,YMPB_ENABLE_WITH_BLOCKER:!0,YMPB_CACHE_SP_THRESHOLD:.75,ENUM_SCHAIN_VALIDATION:"strict",YMPB_PUBLISHER_ID:"",YMPB_ENABLE_FLUID_SIZE:!0,YMPB_ENABLE_SMALLER_SIZE:!0,YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0,USER_SYNC_FILTER:{iframe:{bidders:"*",filter:"include"}},YMPB_USP_CONTAINER:"#ymbp_usp_iogames_next",YMPB_BASE_INDEX:"99998",YMPB_CUSTOM_CSS:'ins[data-google-query-id]::before {\n    content: "\\00d7";\n    display: block;\n    width: 48px;\n    height: 48px;\n    position: absolute;\n    right: 20px;\n    top:0;\n    z-index: 1;\n    font-size: 38px;\n    color: #ccc;\n    text-shadow: 0px 0px 1px #000;\n    pointer-events: none;\n}',
YMPB_CUSTOM_JS:null,REFRESH_IGNORE_VIEW_STATUS:["triplelift"],SWAP_IGNORE_BIDDERS:["triplelift"],YMPB_VARIANT_NOTES:"Timeout 3000",ENABLE_INTERSTITIAL:!0,PREROLL_RETRY:1,YMPB_FORCE_REFRESH:240,GA_ACCOUNT:"UA-77565304-1"},mobile:{YMPB_ENABLE_FLUID_SIZE:!1,YMPB_CUSTOM_CSS:"",YMPB_ENABLE_SWAPPING:!1,ENABLE_INTERSTITIAL:!1},tablet:{}},geo_target_options:{US:{desktop:{YMPB_DEFAULT_REFRESHRATE:26,YMPB_MEDREC_TO_MULTI:{multiMode:"dynamic",slotSpacing:20,maxSize:"0x250",maxSlots:2},YMPB_MEDREC_TO_MULTI_NUM:2},
mobile:{YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0},tablet:{}}},case_control:!1,variant_template_id:0},{weight:10,is_main:!1,version:"3.3.0.25",macro_options:{desktop:{YMPB_AD_FOOTER_TEXT:"powered by <b>Yolla</b>",ADHESION_ENABLECLOSE:!1,BIDDERS:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),YMPB_VARIANT:"63",ENABLE_ADSENCE_PASSBACK:!1,BIDDER_LABELS_INITING:"33across appnexus appnexus_v appnexus_v2 districtm_v ix openx openx_v pulsepoint rubicon triplelift".split(" "),
BIDDER_LABELS_PRECACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_REFRESHING:"33across appnexus appnexus_v appnexus_v2 ix openx openx_v pulsepoint rubicon triplelift".split(" "),BIDDER_LABELS_INITCACHING:"33across appnexus ix openx pulsepoint rubicon triplelift".split(" "),ADHESION_BG_COLOR:"rgba(64, 68, 81,0.7)",YMPB_REFRESHRATE_MIN:25,YMPB_REFRESH_UNVIEWED:!0,YMPB_REFRESH_NOT_INVIEW:!0,YMPB_REFRESH_RATE_NOFILL:60,REFRESH_IGNORE_ADX_VIEW_STATUS:!1,YMPB_PRECACHE_MAX_BIDS:200,
YMPB_FILTER_MIN_CPM:.07,YMPB_BID_CACHE_MIN_TTL_OVERRIDE:300,YMPB_BID_CACHE_TTL:900,YMPB_PRECACHE_INTERVAL:900,SWAPPING_INTERVAL:3,YMPB_VIDEO_AUTOPLAY:!0,YMPB_VIDEO_VOLUME:100,YMPB_VIDEO_SKIP_TIMER:30,YMPB_VIDEO_TIMEOUT:10,DYNAMIC_LOAD_SCREEN_VH:4,DYNAMIC_LOAD_SCREEN_VH_ABOVE:5,DYNAMIC_DESTROY_VIEWED:!1,YMPB_AUCTION_TIMEOUT:2E3,DISABLE_AJAX_TIMEOUT:!0,CHECKING_BETTER_ADS:!1,ENABLE_S2S:!1,YMPB_ENABLE_ADDITIONAL_BIDS:3,YMPB_USE_CACHE_POSTAUCTION:!0,YMPB_REFRSH_UNVIEWED_WITH_LV:!1,YMPB_COLLAPSE_DYNAMIC_ABOVE:!1,
YMPB_ENABLE_BLOCKTHROUGH:!0,YMPB_ENABLE_WITH_BLOCKER:!0,YMPB_CACHE_SP_THRESHOLD:.75,ENUM_SCHAIN_VALIDATION:"strict",YMPB_PUBLISHER_ID:"",YMPB_ENABLE_FLUID_SIZE:!0,YMPB_ENABLE_SMALLER_SIZE:!0,YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0,USER_SYNC_FILTER:{iframe:{bidders:"*",filter:"include"}},YMPB_USP_CONTAINER:"#ymbp_usp_iogames_next",YMPB_BASE_INDEX:"99998",YMPB_CUSTOM_CSS:'ins[data-google-query-id]::before {\n    content: "\\00d7";\n    display: block;\n    width: 48px;\n    height: 48px;\n    position: absolute;\n    right: 20px;\n    top:0;\n    z-index: 1;\n    font-size: 38px;\n    color: #ccc;\n    text-shadow: 0px 0px 1px #000;\n    pointer-events: none;\n}',
YMPB_CUSTOM_JS:null,REFRESH_IGNORE_VIEW_STATUS:["triplelift"],SWAP_IGNORE_BIDDERS:["triplelift"],YMPB_VARIANT_NOTES:"GPID Enabled",ENABLE_INTERSTITIAL:!0,PREROLL_RETRY:1,YMPB_FORCE_REFRESH:240,GA_ACCOUNT:"UA-77565304-1"},mobile:{YMPB_ENABLE_FLUID_SIZE:!1,YMPB_CUSTOM_CSS:"",YMPB_ENABLE_SWAPPING:!1,ENABLE_INTERSTITIAL:!1},tablet:{}},geo_target_options:{US:{desktop:{YMPB_DEFAULT_REFRESHRATE:26,YMPB_MEDREC_TO_MULTI:{multiMode:"dynamic",slotSpacing:20,maxSize:"0x250",maxSlots:2},YMPB_MEDREC_TO_MULTI_NUM:2},
mobile:{YMPB_MEDREC_TO_MULTI:{},YMPB_MEDREC_TO_MULTI_NUM:0},tablet:{}}},case_control:!1,variant_template_id:0}]);var N=null,Ca=null;m.init(function(){N=new xa(m.getOption("DIAGNOSIS_GA_ACCOUNT")||"UA-125030536-7",m.$userSession.get("uuid"));Ca=new ya(m);m.$userSession.isNew&&(N.send("ytt.send","event","Variant",m.getOption("YMPB_VARIANT"),window.location.hostname,1),Ca.send("ytt.send","event","Variant",m.getOption("YMPB_VARIANT"),window.location.hostname,1));var c={limits:{appnexus:0,rubicon:0,ix:0,
triplelift:0,"33across":0,openx:0,pulsepoint:0,appnexus_v:0,openx_v:0,appnexus_v2:0},ad_units:[{code:"desktop-adhesion",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331444"}},{bidder:"rubicon",labelAny:["initing","precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246224",zoneId:"1216966"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422745",size:[728,
90]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_D_728x90",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"deOs7ootCr6y4haKkGJozW",productId:"siab"}},{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"540887183",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing",
"precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685287}}],mediaTypes:["banner"]},{code:"desktop-inarticle-leaderboard",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331444"}},{bidder:"rubicon",labelAny:["initing","precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246224",zoneId:"1216966"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422745",
size:[728,90]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_D_728x90",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"deOs7ootCr6y4haKkGJozW",productId:"siab"}},{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"540887183",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",
labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685287}}],mediaTypes:["banner"]},{code:"desktop-inarticle-medrec",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331445"}},{bidder:"rubicon",labelAny:["initing","precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246224",zoneId:"1216958"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",
params:{siteId:"422743",size:[300,250]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_D_300x250",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"c8n_VWotCr6ykUaKlId8sQ",productId:"siab"}},{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"540887184",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},
{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685286}}],mediaTypes:["banner"]},{code:"desktop-leaderboard-template",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331444"}},{bidder:"rubicon",labelAny:["initing","precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246224",zoneId:"1216966"}},{bidder:"ix",labelAny:["initing","precaching",
"refreshing"],alias:"ix",params:{siteId:"422745",size:[728,90]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_D_728x90",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"deOs7ootCr6y4haKkGJozW",productId:"siab"}},{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"540887183",delDomain:"yolla-d.openx.net",customParams:{},
customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685287}}],mediaTypes:["banner"]},{code:"desktop-medrec-template",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331445"}},{bidder:"rubicon",labelAny:["initing","precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246224",zoneId:"1216958"}},{bidder:"ix",labelAny:["initing",
"precaching","refreshing"],alias:"ix",params:{siteId:"422743",size:[300,250]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_D_300x250",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"c8n_VWotCr6ykUaKlId8sQ",productId:"siab"}},{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"540887184",delDomain:"yolla-d.openx.net",
customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685286}}],mediaTypes:["banner"]},{code:"desktop-oop",bids:[],mediaTypes:["banner"]},{code:"desktop-preroll",bids:[{bidder:"appnexus_v",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331442",video:{}}},{bidder:"openx_v",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"540887180",
delDomain:"yolla-d.openx.net",customParams:{},customFloor:null,doNotTrack:null,coppa:null,openrtb:{}}},{bidder:"appnexus_v2",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331443",video:{}}}],mediaTypes:["video"]},{code:"desktop-sticky-template",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331445"}},{bidder:"rubicon",labelAny:["initing","precaching","refreshing"],
alias:"rubicon",params:{accountId:"19700",siteId:"246224",zoneId:"1216958"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422743",size:[300,250]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_D_300x250",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"c8n_VWotCr6ykUaKlId8sQ",productId:"siab"}},{bidder:"openx",
labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"540887184",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685286}}],mediaTypes:["banner"]},{code:"mobile-adhesion",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331448"}},{bidder:"rubicon",labelAny:["initing","precaching",
"refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246230",zoneId:"1216984"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422749",size:[320,50]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_HDX",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"dnn3oqotCr6yoQaKkv7mNO",productId:"siab"}},{bidder:"openx",
labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"558603906",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685289}}],mediaTypes:["banner"]},{code:"mobile-inarticle-leaderboard",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331448"}},{bidder:"rubicon",labelAny:["initing",
"precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246230",zoneId:"1216984"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422749",size:[320,50]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_HDX",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"dnn3oqotCr6yoQaKkv7mNO",productId:"siab"}},
{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"558603906",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685289}}],mediaTypes:["banner"]},{code:"mobile-inarticle-medrec",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331449"}},{bidder:"rubicon",labelAny:["initing",
"precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246230",zoneId:"1216978"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422747",size:[300,250]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_M_300x250",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"dwi_88otCr6ykUaKlId8sQ",productId:"siab"}},
{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"558603907",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685288}}],mediaTypes:["banner"]},{code:"mobile-leaderboard-template",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331448"}},{bidder:"rubicon",labelAny:["initing",
"precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246230",zoneId:"1216984"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422749",size:[320,50]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_HDX",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"dnn3oqotCr6yoQaKkv7mNO",productId:"siab"}},
{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"558603906",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685289}}],mediaTypes:["banner"]},{code:"mobile-medrec-template",bids:[{bidder:"appnexus",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331449"}},{bidder:"rubicon",labelAny:["initing",
"precaching","refreshing"],alias:"rubicon",params:{accountId:"19700",siteId:"246230",zoneId:"1216978"}},{bidder:"ix",labelAny:["initing","precaching","refreshing"],alias:"ix",params:{siteId:"422747",size:[300,250]}},{bidder:"triplelift",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"triplelift",params:{inventoryCode:"IoGame_M_300x250",floor:null}},{bidder:"33across",labelAny:["initing","precaching","refreshing"],alias:"33across",params:{siteId:"dwi_88otCr6ykUaKlId8sQ",productId:"siab"}},
{bidder:"openx",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"558603907",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null}},{bidder:"pulsepoint",labelAny:["initing","precaching","refreshing"],alias:"pulsepoint",params:{cp:561978,ct:685288}}],mediaTypes:["banner"]},{code:"mobile-oop",bids:[],mediaTypes:["banner"]},{code:"mobile-preroll",bids:[{bidder:"appnexus_v",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331446",
video:{}}},{bidder:"openx_v",labelAny:["initing","precaching","refreshing"],alias:"openx",params:{unit:"556580836",delDomain:"yolla-d.openx.net",customParams:{},customFloor:null,doNotTrack:null,coppa:null,openrtb:{}}},{bidder:"appnexus_v2",labelAny:["initing","refreshing","precaching","precaching_2"],alias:"appnexus",params:{placementId:"20331447",video:{}}}],mediaTypes:["video"]}]};if("string"===typeof m.tagUrl){m.setOption("S2S_CONFIG",{bidders:[],bidderControl:{},bidderControlRefresh:{}});var a=
m.tagUrl;if(m.$deviceDetector.isTablet){var d=m.getOption("YMPB_TABLET_SLOTS");m.$deviceDetector.slotType=d}(d=la(a))&&m.setOption("YMPB_TEMPLATE_VERSION",d);0<=ma("3.0.0",d)||"0.0.0"===d?na(a,c):(0>ma("2.8.22",d)&&(Array.prototype.forEach.call(l.command,function(b){l.que.push(b)}),l.command=l.que),window.BID_BIAS={},window.JSON_DATA=[c],window.YMPB_OPTIONS=m.getOptions(),window.BIDS_ADJ=m.getOption("BIDSADJUSTMENT"),window.DFP_PUBLISHER_UNIT=m.getOption("DFP_PUBLISHER_UNIT"),window.YMPB_TEMPLATE_CSS=
m.getOption("YMPB_TEMPLATE_CSS"),window.YMPB_OPTION_TRACKING=m.getOption("YMPB_OPTION_TRACKING"),na(a))}});l.setVersion=function(c){m.switchToVersion(c)};l.setCase=function(c){m.$userSession.cv0=0;m.switchToCase(c)};l.preroll=function(c,a){l.command.push(function(){try{l.instream("preroll",c,a)}catch(d){a.call(void 0,{error:d})}})};l.requestVideoBids=function(c,a,d){l.command.push(function(){try{l.getVast("preroll",a,d)}catch(b){d.call(void 0,c)}})};l.pixelPing=function(c,a,d,b,e,g,f){l.que.push(function(){N&&
N.send(c,a,d,b,e,g,f)})};l.getOption=function(c){m.getOption(c)};l.removeOption=function(c){m.setOption(c,null)};l.setOption=function(c,a){m.setOption(c,a,!0)};l.getOptions=function(){return m.getOptions()};l.options=function(){return m.getOptions()};l.getVersion=function(){return m.tagUrl};l.getTagVersion=function(){return la(m.tagUrl)}})();
